# Generated by Django 4.0.1 on 2022-01-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('C', 'completed'), ('P', 'pending')], max_length=2),
        ),
    ]
